2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_setup.py:_flush():69] setting env: {}
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_setup.py:_flush():69] setting login settings: {}
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_init.py:_log_setup():336] Logging user logs to /Users/tatsukichi/InvertibleTargetPropagation/code/wandb/run-20211215_021110-2b6hzyzi/logs/debug.log
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_init.py:_log_setup():337] Logging internal logs to /Users/tatsukichi/InvertibleTargetPropagation/code/wandb/run-20211215_021110-2b6hzyzi/logs/debug-internal.log
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_init.py:init():369] calling init triggers
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-12-15 02:11:10,467 INFO    MainThread:13822 [wandb_init.py:init():418] starting backend
2021-12-15 02:11:10,467 INFO    MainThread:13822 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-15 02:11:10,476 INFO    MainThread:13822 [backend.py:ensure_launched():132] starting backend process...
2021-12-15 02:11:10,483 INFO    MainThread:13822 [backend.py:ensure_launched():137] started backend process with pid: 13831
2021-12-15 02:11:10,485 INFO    MainThread:13822 [wandb_init.py:init():423] backend started and connected
2021-12-15 02:11:10,489 INFO    MainThread:13822 [wandb_init.py:init():465] updated telemetry
2021-12-15 02:11:10,489 INFO    MainThread:13822 [wandb_init.py:init():484] communicating current version
2021-12-15 02:11:11,405 INFO    MainThread:13822 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-15 02:11:11,405 INFO    MainThread:13822 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-12-15 02:11:11,639 INFO    MainThread:13822 [wandb_init.py:init():522] starting run threads in backend
2021-12-15 02:11:16,644 INFO    MainThread:13822 [wandb_run.py:_console_start():1565] atexit reg
2021-12-15 02:11:16,644 INFO    MainThread:13822 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-12-15 02:11:16,645 INFO    MainThread:13822 [wandb_run.py:_redirect():1417] Redirecting console.
2021-12-15 02:11:16,646 INFO    MainThread:13822 [wandb_run.py:_redirect():1479] Redirects installed.
2021-12-15 02:11:16,646 INFO    MainThread:13822 [wandb_init.py:init():546] run started, returning control to user process
2021-12-15 02:11:16,646 INFO    MainThread:13822 [wandb_run.py:_config_callback():787] config_cb None None {'problem': 'classification-70000', 'algorithm': 'DTTP', 'epochs': 100, 'batchsize': 128, 'seed': 39, 'depth': 4, 'in_dim': 784, 'hid_dim': 256, 'out_dim': 10, 'activation function': 'leakyrelu', 'stepsize': 0.001, 'direct depth': 2, 'learning rate (backward)': 0.001, 'epochs (backward)': 5, 'sigma (backward)': 0.01}
2021-12-15 02:13:05,804 INFO    MainThread:13822 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-12-15 02:13:05,806 INFO    MainThread:13822 [wandb_run.py:_restore():1507] restore
2021-12-15 02:13:08,015 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1104
  total_bytes: 1104
}

2021-12-15 02:13:08,943 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1104
  total_bytes: 23270
}

2021-12-15 02:13:09,309 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,412 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,514 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,617 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,722 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,826 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:09,933 INFO    MainThread:13822 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 23270
  total_bytes: 23270
}

2021-12-15 02:13:11,190 INFO    MainThread:13822 [wandb_run.py:_show_files():1879] logging synced files
